spring:
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://account
          predicates:
            - Path=/api/account/**
        - id: customer
          uri: lb://customer
          predicates:
            - Path=api/customers/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true

  instance:
    preferIpAddress: true
    hostname: localhost
