spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account
          predicates:
            - Path=/api/account/**
        - id: customer-service
          uri: lb://customers
          predicates:
            - Path=api/customer/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
