spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account
          predicates:
            - Path=/account/**
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customers/**

      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true

  instance:
    preferIpAddress: true
    hostname: localhost


