spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account
          predicates:
            - Path=/api/account/**
        - id: customer-service
          uri: lb://customer
          predicates:
            - Path=api/customer/**


server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
